# This file was generated by RNOH autolinking.
# DO NOT modify it manually, your changes WILL be overwritten.
cmake_minimum_required(VERSION 3.5)

# @actor RNOH_APP
function(autolink_libraries target)
    add_subdirectory("${OH_MODULES_DIR}/@oh-rn/stripe-react-native/src/main/cpp" ./stripe_react_native)
    add_subdirectory("${OH_MODULES_DIR}/@react-native-ohos/react-native-webview/src/main/cpp" ./rnoh_webview)

    set(AUTOLINKED_LIBRARIES
        stripe_react_native
        rnoh_webview
    )

    foreach(lib ${AUTOLINKED_LIBRARIES})
        target_link_libraries(${target} PUBLIC ${lib})
    endforeach()
endfunction()
