/*
 * This file was generated by RNOH autolinking.
 * DO NOT modify it manually, your changes WILL be overwritten.
 */
// clang-format off
#pragma once
#include "RNOH/Package.h"
#include "StripeReactNativePackage.h"
#include "WebViewPackage.h"

std::vector<rnoh::Package::Shared> createRNOHPackages(const rnoh::Package::Context &ctx) {
  return {
    std::make_shared<rnoh::StripeReactNativePackage>(ctx),
    std::make_shared<rnoh::WebViewPackage>(ctx),
  };
}
